name: Build And Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: yarn install --immutable --immutable-cache

      - name: Build Manifest v2
        run: |
          yarn run build:mv2
          7za a mv2.zip ./dist/*

      - name: Build Manifest v3
        run: |
          yarn run build:mv3
          7za a mv3.zip ./dist/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mv2.zip
            mv3.zip