name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Manifest v2
        run: |
          yarn run build:mv2
          (cd dist && zip -1 -r ../mv2.zip .)

      - name: Build Manifest v3
        run: |
          yarn run build:mv3
          (cd dist && zip -1 -r ../mv3.zip .)

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mv2.zip
            mv3.zip
          generate_release_notes: true
